services:
  remote-cli-new:
    image: oshadmon/gui:latest
    container_name: gui
    restart: always
    stdin_open: true
    tty: true
    networks:
      - mynetwork
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
    volumes:
      - gui-vol:/app/CLI/Local-CLI/local-cli-backend/static/
  edgelake-node:
    image: anylogco/edgelake:latest
    restart: always
    container_name: edgelake-node
    env_file:
      - ../docker-makefiles/edgelake_generic.env
      - .env
    stdin_open: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    tty: true
    networks:
      - mynetwork
    ports:
      - "32548:32548"
      - "32549:32549"
    volumes:
      - nebula-overlay:/app/nebula
      - edgelake-node-anylog:/app/EdgeLake/anylog
      - edgelake-node-blockchain:/app/EdgeLake/blockchain
      - edgelake-node-data:/app/EdgeLake/data
      - edgelake-node-local-scripts:/app/deployment-scripts
      - gui-vol:/app/CLI/Local-CLI/local-cli-backend/static/
      - ./CLI/Local-CLI/local-cli-backend/presets.json:/app/CLI/Local-CLI/local-cli-backend/presets.json
      - ./CLI/Local-CLI/local-cli-backend/preset_groups.json:/app/CLI/Local-CLI/local-cli-backend/preset_groups.json
      - ./CLI/Local-CLI/local-cli-backend/bookmarks.json:/app/CLI/Local-CLI/local-cli-backend/bookmarks.json
      - ./CLI/Local-CLI/local-cli-backend/users.json:/app/CLI/Local-CLI/local-cli-backend/users.json


volumes:
  edgelake-node-anylog:
  edgelake-node-blockchain:
  edgelake-node-data:
  edgelake-node-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
  gui-vol:

networks:
  mynetwork:
    driver: bridge
